/**
 * TanStack Router Configuration
 * 
 * This file creates the router instance with type-safe routing.
 * Routes are auto-generated from the src/routes/ directory.
 */
import { createRouter } from '@tanstack/react-router'
import { QueryClient } from '@tanstack/react-query'

// Import the generated route tree (will be generated by vite plugin)
import { routeTree } from './routeTree.gen'

// Create a query client for router context
const queryClient = new QueryClient()

// Create the router
export const router = createRouter({
  routeTree,
  context: {
    queryClient,
  },
  defaultPreload: 'intent',
  scrollRestoration: true,
})

// Register the router for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
